In [1]:
#import necessary libraries
import re
import pandas as pd
from datetime import datetime

In [2]:
#READ and print out the data

movies = pd.read_csv('movies.csv')
movies

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN
9995,Arcane,(2021– ),"\nAnimation, Action, Adventure",NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN
9996,Heart of Invictus,(2022– ),"\nDocumentary, Sport",NaN,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN
9997,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN
9998,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN

In [3]:
#split the year column to start and end year

def extract_years(year_val):
    try:
        years = re.findall(r'\d{4}', str(year_val))  # find all 4-digit numbers
        
        if not years:
            return pd.Series([None, None])
        
        start = int(years[0])
        
        # Check if there is a second year in the string
        if len(years) > 1:
            end = int(years[1])
        else:
            # Check if original string ends with a dash (meaning ongoing series)
            if str(year_val).strip().endswith('– )') or str(year_val).strip().endswith(' )'):
                end = datetime.now().year # ongoing, so end year is unknown
            else:
                # Single year case
                end = start
        
        return pd.Series([start, end])
    
    except:
        return pd.Series([None, None])

# Apply the function and drop the original YEAR column
movies[['start_year', 'end_year']] = movies['YEAR'].apply(extract_years)
movies.drop(columns=['YEAR'], inplace=True)

In [4]:
#define a function that removes the \n woth a space
def remove_newlines (rem):
    return rem.applymap(lambda x: x.replace('\n', ' ') if isinstance(x, str) else x)

movies = remove_newlines(movies)

C:\Users\Xcuuvy\AppData\Local\Temp\ipykernel_8376\2602743037.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return rem.applymap(lambda x: x.replace('\n', ' ') if isinstance(x, str) else x)

In [5]:
#check for nans values
print(movies.isna().sum())

MOVIES           0
GENRE           80
RATING        1820
ONE-LINE         0
STARS            0
VOTES         1820
RunTime       2958
Gross         9539
start_year     748
end_year       748
dtype: int64

In [6]:
#delete the gross columns since it mostly contains nans
movies.drop(columns=['Gross'], inplace=True)

In [7]:
movies

,MOVIES,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,start_year,end_year
0,Blood Red Sky,"Action, Horror, Thriller",6.1,A woman with a mysterious illness is forced i...,Director: Peter Thorwarth | Stars: P...,"21,062",121.0,2021.0,2021.0
1,Masters of the Universe: Revelation,"Animation, Action, Adventure",5.0,The war for Eternia begins again in what may ...,"Stars: Chris Wood, Sarah Mi...","17,870",25.0,2021.0,2025.0
2,The Walking Dead,"Drama, Horror, Thriller",8.2,Sheriff Deputy Rick Grimes wakes up from a co...,"Stars: Andrew Lincoln, Norm...","885,805",44.0,2010.0,2022.0
3,Rick and Morty,"Animation, Adventure, Comedy",9.2,An animated series that follows the exploits ...,"Stars: Justin Roiland, Chri...","414,849",23.0,2013.0,2025.0
4,Army of Thieves,"Action, Crime, Horror",NaN,"A prequel, set before the events of Army of t...",Director: Matthias Schweighöfer | St...,NaN,NaN,2021.0,2021.0
...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,"Adventure, Drama, Fantasy",NaN,Add a Plot,Stars: Morgan Taylor Campbel...,NaN,NaN,2021.0,2025.0
9995,Arcane,"Animation, Action, Adventure",NaN,Add a Plot,,NaN,NaN,2021.0,2025.0
9996,Heart of Invictus,"Documentary, Sport",NaN,Add a Plot,Director: Orlando von Einsiedel | St...,NaN,NaN,2022.0,2025.0
9997,The Imperfects,"Adventure, Drama, Fantasy",NaN,Add a Plot,Director: Jovanka Vuckovic | Stars: ...,NaN,NaN,2021.0,2025.0
9998,The Imperfects,"Adventure, Drama, Fantasy",NaN,Add a Plot,Director: Jovanka Vuckovic | Stars: ...,NaN,NaN,2021.0,2025.0

In [8]:
#check for nans values
print(movies.isna().sum())

MOVIES           0
GENRE           80
RATING        1820
ONE-LINE         0
STARS            0
VOTES         1820
RunTime       2958
start_year     748
end_year       748
dtype: int64

In [9]:
#check how many movies in theone line column has no plot

c = 0
for a in movies['ONE-LINE']:
    if isinstance(a, str) and a.strip() == "Add a Plot":
        c += 1
print(f'number of  add a plot in column one line {c}')

number of  add a plot in column one line 1265

In [10]:
#drops rows without a plot
# Remove rows where 'ONE-LINE' equals 'Add a Plot' after stripping whitespace
movies = movies[~movies['ONE-LINE'].str.strip().eq("Add a Plot")]

In [11]:
movies.size

78606

In [12]:
#check for nans values
print(movies.isna().sum())

MOVIES           0
GENRE           49
RATING         932
ONE-LINE         0
STARS            0
VOTES          932
RunTime       1905
start_year     465
end_year       465
dtype: int64

In [13]:
#drops all rows with nans
movies.dropna(inplace=True)

C:\Users\Xcuuvy\AppData\Local\Temp\ipykernel_8376\285533765.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies.dropna(inplace=True)

In [14]:
movies.size

59760

In [15]:
#check for nans values
print(movies.isna().sum())

MOVIES        0
GENRE         0
RATING        0
ONE-LINE      0
STARS         0
VOTES         0
RunTime       0
start_year    0
end_year      0
dtype: int64

In [16]:
movies.columns

Index(['MOVIES', 'GENRE', 'RATING', 'ONE-LINE', 'STARS', 'VOTES', 'RunTime',
       'start_year', 'end_year'],
      dtype='object')

In [17]:
movies.dtypes

MOVIES         object
GENRE          object
RATING        float64
ONE-LINE       object
STARS          object
VOTES          object
RunTime       float64
start_year    float64
end_year      float64
dtype: object

In [18]:
# Convert 'VOTES' by removing commas and then converting to integer
movies['VOTES'] = movies['VOTES'].str.replace(',', '').astype(int)

C:\Users\Xcuuvy\AppData\Local\Temp\ipykernel_8376\1786778330.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['VOTES'] = movies['VOTES'].str.replace(',', '').astype(int)

In [19]:
movies.dtypes

MOVIES         object
GENRE          object
RATING        float64
ONE-LINE       object
STARS          object
VOTES           int32
RunTime       float64
start_year    float64
end_year      float64
dtype: object

In [20]:
# Convert 'start_year' to integer
movies['start_year'] = movies['start_year'].astype(int)

# Convert 'end_year' to integer
movies['end_year'] = movies['end_year'].astype(int)

# Convert 'RunTime' to integer
movies['RunTime'] = movies['RunTime'].astype(int)

C:\Users\Xcuuvy\AppData\Local\Temp\ipykernel_8376\1744389516.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['start_year'] = movies['start_year'].astype(int)
C:\Users\Xcuuvy\AppData\Local\Temp\ipykernel_8376\1744389516.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['end_year'] = movies['end_year'].astype(int)
C:\Users\Xcuuvy\AppData\Local\Temp\ipykernel_8376\1744389516.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['RunTime'] = movies['RunTime'].astype(int)

In [21]:
movies.dtypes

MOVIES         object
GENRE          object
RATING        float64
ONE-LINE       object
STARS          object
VOTES           int32
RunTime         int32
start_year      int32
end_year        int32
dtype: object

In [22]:
movies.duplicated().sum() # Counts fully duplicate rows

0

In [23]:
movies

,MOVIES,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,start_year,end_year
0,Blood Red Sky,"Action, Horror, Thriller",6.1,A woman with a mysterious illness is forced i...,Director: Peter Thorwarth | Stars: P...,21062,121,2021,2021
1,Masters of the Universe: Revelation,"Animation, Action, Adventure",5.0,The war for Eternia begins again in what may ...,"Stars: Chris Wood, Sarah Mi...",17870,25,2021,2025
2,The Walking Dead,"Drama, Horror, Thriller",8.2,Sheriff Deputy Rick Grimes wakes up from a co...,"Stars: Andrew Lincoln, Norm...",885805,44,2010,2022
3,Rick and Morty,"Animation, Adventure, Comedy",9.2,An animated series that follows the exploits ...,"Stars: Justin Roiland, Chri...",414849,23,2013,2025
5,Outer Banks,"Action, Crime, Drama",7.6,A group of teenagers from the wrong side of t...,"Stars: Chase Stokes, Madely...",25858,50,2020,2025
...,...,...,...,...,...,...,...,...,...
9959,Sexify,"Comedy, Drama",6.8,"Monika's idea for gathering data is a hit, bu...",Director: Kalina Alabrudzinska | Sta...,108,38,2021,2025
9960,Sexify,"Comedy, Drama",7.1,After facing their parents at Easter breakfas...,Director: Kalina Alabrudzinska | Sta...,103,37,2021,2025
9961,Sexify,"Comedy, Drama",6.9,After getting an anonymous tip about the copu...,Director: Kalina Alabrudzinska | Sta...,96,40,2021,2025
9962,Sexify,"Comedy, Drama",7.1,The big pitch at the university tech competit...,Director: Kalina Alabrudzinska | Sta...,100,47,2021,2025
9963,Castlevania,"Animation, Action, Adventure",8.2,Lenore urges Hector to not test Camilla's pat...,Director: Sam Deats | Stars: Richard...,911,24,2017,2021

In [25]:
#counts number of duplicate movie titles
duplicate = movies['MOVIES'].duplicated().sum()
print(f"Number of duplicate movie titles: {duplicate}")

Number of duplicate movie titles: 1553

In [26]:
# First, identify the titles that are duplicated
duplicated_titles = movies[movies['MOVIES'].duplicated(keep=False)]['MOVIES'].unique()
print(f"Found {len(duplicated_titles)} unique movie titles that have duplicates.")

#  show only rows with these duplicated titles
movies_with_duplicate_titles = movies[movies['MOVIES'].isin(duplicated_titles)].sort_values(by=['MOVIES', 'start_year'])

# Display a sample of these duplicate titles.
print("\n--- Sample of Rows with Duplicated Titles ---")
# Display the first 20 rows of these duplicates, and specifically relevant columns
print(movies_with_duplicate_titles[['MOVIES', 'start_year', 'end_year', 'RATING', 'VOTES', 'RunTime']].head(20))

Found 221 unique movie titles that have duplicates.

--- Sample of Rows with Duplicated Titles ---
                         MOVIES  start_year  end_year  RATING  VOTES  RunTime
7378             13 Reasons Why        2017      2020     5.7   1798       59
7423             13 Reasons Why        2017      2020     5.7   1597       58
7789             13 Reasons Why        2017      2020     5.1   1714       59
8134             13 Reasons Why        2017      2020     6.2   1619       57
8196             13 Reasons Why        2017      2020     6.1   1507       57
8197             13 Reasons Why        2017      2020     6.6   1694       61
8375             13 Reasons Why        2017      2020     5.6   1635       59
8376             13 Reasons Why        2017      2020     5.9   1420       60
8395             13 Reasons Why        2017      2020     6.8   1640       60
8396             13 Reasons Why        2017      2020     7.7   2312       98
7207   3Below: Tales of Arcadia        2018      2019     7.9    143       22
7283   3Below: Tales of Arcadia        2018      2019     8.0    141       22
7284   3Below: Tales of Arcadia        2018      2019     7.5    136       22
7285   3Below: Tales of Arcadia        2018      2019     7.6    137       22
7286   3Below: Tales of Arcadia        2018      2019     7.8    139       22
7287   3Below: Tales of Arcadia        2018      2019     7.2    135       22
7288   3Below: Tales of Arcadia        2018      2019     8.0    146       22
7289   3Below: Tales of Arcadia        2018      2019     7.2    133       22
7290   3Below: Tales of Arcadia        2018      2019     8.3    137       23
7291   3Below: Tales of Arcadia        2018      2019     8.5    142       22

In [27]:
#since the duplivate movies have different ratings and votes, it means it is a series and each entries is for an episode of the series

In [32]:
#print and save a the dataframe sorted by rating in ascending order
movies_sorted_by_rating = movies.sort_values(by='RATING', ascending=False)

movies_sorted_by_rating.to_excel('movies_sorted_by_rating.xlsx', index = False)